# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `md5' in source file `md5.m'.
# Generated by Mercury compiler version 22.01-focal1
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   type_repn self dep
Mercury/optdates/md5.optdate Mercury/trans_opt_dates/md5.trans_opt_date md5.err Mercury/c_dates/md5.c_date Mercury/java_dates/md5.java_date : \
		md5.m \
	\
		Mercury/ints/builtin.int \
		Mercury/ints/private_builtin.int \
		Mercury/ints/require.int \
	\
		Mercury/ints/md5.int

# RULE mh_and_mih_on_c
md5.mh Mercury/mihs/md5.mih : Mercury/cs/md5.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
Mercury/module_deps/md5.module_dep : Mercury/javas/jmercury/md5.java

else

# RULE module_dep_on_c
Mercury/module_deps/md5.module_dep : Mercury/cs/md5.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
Mercury/dates/md5.date Mercury/date0s/md5.date0 : \
		md5.m \
	\
		Mercury/int3s/builtin.int3 \
		Mercury/int3s/private_builtin.int3 \
		Mercury/int3s/require.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
Mercury/date0s/md5.date0 : \
		md5.m \
	\
		Mercury/int3s/builtin.int3 \
		Mercury/int3s/private_builtin.int3 \
		Mercury/int3s/require.int3

# RULE foreign_deps_for_mh
Mercury/os/md5.$O Mercury/os/md5.pic_o : md5.mh

# RULE int0_on_date0
Mercury/int0s/md5.int0 : Mercury/date0s/md5.date0
	@:

# RULE int_on_date
Mercury/ints/md5.int : Mercury/dates/md5.date
	@:

# RULE int2_on_date
Mercury/int2s/md5.int2 : Mercury/dates/md5.date
	@:

# RULE int3_on_date3
Mercury/int3s/md5.int3 : Mercury/date3s/md5.date3
	@:

# RULE opt_on_opt_date
Mercury/opts/md5.opt : Mercury/optdates/md5.optdate
	@:

# RULE trans_opt_on_trans_opt_date
Mercury/trans_opts/md5.trans_opt : Mercury/trans_opt_dates/md5.trans_opt_date
	@:

# RULE subdir_shorthand_for_.c
.PHONY: md5.c
md5.c : Mercury/cs/md5.c

# RULE subdir_shorthand_for_.$O
.PHONY: md5.$O
md5.$O : Mercury/os/md5.$O

# RULE subdir_shorthand_for_.pic_o
.PHONY: md5.pic_o
md5.pic_o : Mercury/os/md5.pic_o

# RULE subdir_shorthand_for_.java
.PHONY: md5.java
md5.java : Mercury/javas/jmercury/md5.java

# RULE subdir_shorthand_for_.class
.PHONY: md5.class
md5.class : Mercury/classs/jmercury/md5.class

# RULE subdir_shorthand_for_.dll
.PHONY: md5.dll
md5.dll : md5.dll

